services:
  web:
    build: .
    volumes:
      - ./db:/app/db                  # <-- Теперь монтируем папку db, как хочет settings.py!
      - ./staticfiles:/app/staticfiles
    env_file: .env
    ports:
      - "127.0.0.1:8001:8000"
    restart: unless-stopped