upstream django_app {
    server web:8000;
    keepalive 32;
}

server {
    listen 80 default_server;
    server_name _;              # <- Сюда имя нового домена вместо localhost

    # ACME challenge — сюда постучится certbot вечером для проверки
    # владения доменом. Без этого блока выпуск сертификата упадёт с 404.
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location /static/ {
        alias /var/www/static/;
        expires 30d;
        add_header Cache-Control "public, immutable";
        gzip_static on;
    }

    location / {
        proxy_pass http://django_app;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect   off;
        proxy_connect_timeout 60s;
        proxy_send_timeout    60s;
        proxy_read_timeout    60s;
    }
}